server:
  port: 8080
spring:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 192.168.31.101:26379
        - 192.168.31.102:26379
        - 192.168.31.103:26379
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数,默认8个，（使用负值表示没有限制）
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-active: 100
        min-idle: 0
    timeout: 6000ms
    host: hadoop1
    port: 6379
  datasource:
    url: jdbc:mysql://hadoop1:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wangzili
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
logging:
  level:
    com.vshare.springboot.Mapper : debug
curator:
  retryCount: 5 #重试次数
  elapsedTimeMs: 5000 #重试间隔时间
  connectString: hadoop1:2181,hadoop2:2181,hadoop3:2181 # zookeeper 地址
  sessionTimeoutMs: 60000 # session超时时间
  connectionTimeoutMs: 5000 # 连接超时时间